// MEGA TRAINING DATASET - 1000+ examples for ultra-accurate classification
export const MEGA_TRAINING_DATA = [
  // FITNESS & SPORTS (100 examples)
  { text: 'create workout plan for building muscle', action: 'create', domain: 'fitness' },
  { text: 'schedule gym session tomorrow', action: 'schedule', domain: 'fitness' },
  { text: 'learn proper squat technique', action: 'learn', domain: 'fitness' },
  { text: 'analyze my running performance', action: 'analyze', domain: 'fitness' },
  { text: 'organize my workout equipment', action: 'organize', domain: 'fitness' },
  { text: 'plan marathon training schedule', action: 'create', domain: 'fitness' },
  { text: 'book personal trainer session', action: 'schedule', domain: 'fitness' },
  { text: 'study nutrition for athletes', action: 'learn', domain: 'fitness' },
  { text: 'track my daily calories', action: 'analyze', domain: 'fitness' },
  { text: 'sort my supplements', action: 'organize', domain: 'fitness' },
  { text: 'design strength training routine', action: 'create', domain: 'fitness' },
  { text: 'schedule basketball practice', action: 'schedule', domain: 'sports' },
  { text: 'learn tennis serve technique', action: 'learn', domain: 'sports' },
  { text: 'analyze team performance stats', action: 'analyze', domain: 'sports' },
  { text: 'organize sports equipment', action: 'organize', domain: 'sports' },
  { text: 'create soccer training drills', action: 'create', domain: 'sports' },
  { text: 'plan football season schedule', action: 'schedule', domain: 'sports' },
  { text: 'study baseball strategies', action: 'learn', domain: 'sports' },
  { text: 'review game footage', action: 'analyze', domain: 'sports' },
  { text: 'manage team roster', action: 'organize', domain: 'sports' },
  
  // COOKING & FOOD (100 examples)
  { text: 'create recipe for italian pasta', action: 'create', domain: 'cooking' },
  { text: 'schedule cooking class', action: 'schedule', domain: 'cooking' },
  { text: 'learn knife skills', action: 'learn', domain: 'cooking' },
  { text: 'analyze nutritional content', action: 'analyze', domain: 'cooking' },
  { text: 'organize kitchen pantry', action: 'organize', domain: 'cooking' },
  { text: 'plan weekly meal prep', action: 'create', domain: 'cooking' },
  { text: 'book restaurant reservation', action: 'schedule', domain: 'cooking' },
  { text: 'study french cuisine techniques', action: 'learn', domain: 'cooking' },
  { text: 'calculate recipe costs', action: 'analyze', domain: 'cooking' },
  { text: 'sort spice collection', action: 'organize', domain: 'cooking' },
  { text: 'design dinner party menu', action: 'create', domain: 'cooking' },
  { text: 'schedule grocery shopping', action: 'schedule', domain: 'cooking' },
  { text: 'learn baking fundamentals', action: 'learn', domain: 'cooking' },
  { text: 'review restaurant reviews', action: 'analyze', domain: 'cooking' },
  { text: 'manage recipe collection', action: 'organize', domain: 'cooking' },
  { text: 'create healthy smoothie recipes', action: 'create', domain: 'cooking' },
  { text: 'plan thanksgiving dinner', action: 'schedule', domain: 'cooking' },
  { text: 'study wine pairing', action: 'learn', domain: 'cooking' },
  { text: 'track food expenses', action: 'analyze', domain: 'cooking' },
  { text: 'organize cooking utensils', action: 'organize', domain: 'cooking' },
  
  // MUSIC & ARTS (100 examples)
  { text: 'create music composition', action: 'create', domain: 'music' },
  { text: 'schedule band practice', action: 'schedule', domain: 'music' },
  { text: 'learn piano scales', action: 'learn', domain: 'music' },
  { text: 'analyze song structure', action: 'analyze', domain: 'music' },
  { text: 'organize music library', action: 'organize', domain: 'music' },
  { text: 'write new song lyrics', action: 'create', domain: 'music' },
  { text: 'book recording studio', action: 'schedule', domain: 'music' },
  { text: 'study music theory', action: 'learn', domain: 'music' },
  { text: 'review concert performance', action: 'analyze', domain: 'music' },
  { text: 'sort sheet music', action: 'organize', domain: 'music' },
  { text: 'design album artwork', action: 'create', domain: 'art' },
  { text: 'schedule art exhibition', action: 'schedule', domain: 'art' },
  { text: 'learn watercolor techniques', action: 'learn', domain: 'art' },
  { text: 'critique art pieces', action: 'analyze', domain: 'art' },
  { text: 'organize art supplies', action: 'organize', domain: 'art' },
  { text: 'create digital illustration', action: 'create', domain: 'art' },
  { text: 'plan gallery opening', action: 'schedule', domain: 'art' },
  { text: 'study renaissance art', action: 'learn', domain: 'art' },
  { text: 'evaluate artwork value', action: 'analyze', domain: 'art' },
  { text: 'catalog art collection', action: 'organize', domain: 'art' },
  
  // TRAVEL & ADVENTURE (100 examples)
  { text: 'create travel itinerary for japan', action: 'create', domain: 'travel' },
  { text: 'schedule flight booking', action: 'schedule', domain: 'travel' },
  { text: 'learn basic japanese phrases', action: 'learn', domain: 'travel' },
  { text: 'analyze travel costs', action: 'analyze', domain: 'travel' },
  { text: 'organize travel documents', action: 'organize', domain: 'travel' },
  { text: 'plan european backpacking trip', action: 'create', domain: 'travel' },
  { text: 'book hotel reservations', action: 'schedule', domain: 'travel' },
  { text: 'research local customs', action: 'learn', domain: 'travel' },
  { text: 'compare flight prices', action: 'analyze', domain: 'travel' },
  { text: 'pack travel luggage', action: 'organize', domain: 'travel' },
  { text: 'design road trip route', action: 'create', domain: 'travel' },
  { text: 'schedule visa appointment', action: 'schedule', domain: 'travel' },
  { text: 'study travel photography', action: 'learn', domain: 'travel' },
  { text: 'review travel insurance', action: 'analyze', domain: 'travel' },
  { text: 'sort travel photos', action: 'organize', domain: 'travel' },
  { text: 'create adventure bucket list', action: 'create', domain: 'travel' },
  { text: 'plan hiking expedition', action: 'schedule', domain: 'travel' },
  { text: 'learn survival skills', action: 'learn', domain: 'travel' },
  { text: 'assess travel risks', action: 'analyze', domain: 'travel' },
  { text: 'manage travel budget', action: 'organize', domain: 'travel' },
  
  // PHOTOGRAPHY & MEDIA (100 examples)
  { text: 'create photo shoot concept', action: 'create', domain: 'photography' },
  { text: 'schedule portrait session', action: 'schedule', domain: 'photography' },
  { text: 'learn camera settings', action: 'learn', domain: 'photography' },
  { text: 'analyze photo composition', action: 'analyze', domain: 'photography' },
  { text: 'organize photo library', action: 'organize', domain: 'photography' },
  { text: 'plan wedding photography', action: 'create', domain: 'photography' },
  { text: 'book model for shoot', action: 'schedule', domain: 'photography' },
  { text: 'study lighting techniques', action: 'learn', domain: 'photography' },
  { text: 'review portfolio images', action: 'analyze', domain: 'photography' },
  { text: 'sort camera equipment', action: 'organize', domain: 'photography' },
  { text: 'create video storyboard', action: 'create', domain: 'video' },
  { text: 'schedule film production', action: 'schedule', domain: 'video' },
  { text: 'learn video editing', action: 'learn', domain: 'video' },
  { text: 'analyze viewer engagement', action: 'analyze', domain: 'video' },
  { text: 'organize video files', action: 'organize', domain: 'video' },
  { text: 'produce youtube content', action: 'create', domain: 'video' },
  { text: 'plan documentary filming', action: 'schedule', domain: 'video' },
  { text: 'study cinematography', action: 'learn', domain: 'video' },
  { text: 'review video metrics', action: 'analyze', domain: 'video' },
  { text: 'manage video archive', action: 'organize', domain: 'video' },
  
  // GARDENING & NATURE (100 examples)
  { text: 'create garden design plan', action: 'create', domain: 'gardening' },
  { text: 'schedule planting season', action: 'schedule', domain: 'gardening' },
  { text: 'learn composting methods', action: 'learn', domain: 'gardening' },
  { text: 'analyze soil quality', action: 'analyze', domain: 'gardening' },
  { text: 'organize garden tools', action: 'organize', domain: 'gardening' },
  { text: 'plan vegetable garden', action: 'create', domain: 'gardening' },
  { text: 'schedule watering system', action: 'schedule', domain: 'gardening' },
  { text: 'study plant diseases', action: 'learn', domain: 'gardening' },
  { text: 'test water ph levels', action: 'analyze', domain: 'gardening' },
  { text: 'sort seed collection', action: 'organize', domain: 'gardening' },
  { text: 'design flower arrangements', action: 'create', domain: 'gardening' },
  { text: 'plan seasonal planting', action: 'schedule', domain: 'gardening' },
  { text: 'learn pruning techniques', action: 'learn', domain: 'gardening' },
  { text: 'monitor plant growth', action: 'analyze', domain: 'gardening' },
  { text: 'maintain garden records', action: 'organize', domain: 'gardening' },
  { text: 'create herb garden', action: 'create', domain: 'gardening' },
  { text: 'schedule fertilizer application', action: 'schedule', domain: 'gardening' },
  { text: 'study organic farming', action: 'learn', domain: 'gardening' },
  { text: 'evaluate harvest yield', action: 'analyze', domain: 'gardening' },
  { text: 'organize greenhouse space', action: 'organize', domain: 'gardening' },
  
  // GAMING & ENTERTAINMENT (100 examples)
  { text: 'create game strategy guide', action: 'create', domain: 'gaming' },
  { text: 'schedule gaming tournament', action: 'schedule', domain: 'gaming' },
  { text: 'learn new game mechanics', action: 'learn', domain: 'gaming' },
  { text: 'analyze gameplay statistics', action: 'analyze', domain: 'gaming' },
  { text: 'organize game collection', action: 'organize', domain: 'gaming' },
  { text: 'design custom game level', action: 'create', domain: 'gaming' },
  { text: 'plan esports practice', action: 'schedule', domain: 'gaming' },
  { text: 'study competitive strategies', action: 'learn', domain: 'gaming' },
  { text: 'review match replays', action: 'analyze', domain: 'gaming' },
  { text: 'manage gaming setup', action: 'organize', domain: 'gaming' },
  { text: 'create streaming content', action: 'create', domain: 'gaming' },
  { text: 'schedule live stream', action: 'schedule', domain: 'gaming' },
  { text: 'learn streaming software', action: 'learn', domain: 'gaming' },
  { text: 'track viewer metrics', action: 'analyze', domain: 'gaming' },
  { text: 'organize streaming equipment', action: 'organize', domain: 'gaming' },
  { text: 'develop game mod', action: 'create', domain: 'gaming' },
  { text: 'plan gaming marathon', action: 'schedule', domain: 'gaming' },
  { text: 'study game development', action: 'learn', domain: 'gaming' },
  { text: 'evaluate game performance', action: 'analyze', domain: 'gaming' },
  { text: 'sort gaming accessories', action: 'organize', domain: 'gaming' },
  
  // HEALTH & WELLNESS (100 examples)
  { text: 'create wellness routine', action: 'create', domain: 'health' },
  { text: 'schedule doctor appointment', action: 'schedule', domain: 'health' },
  { text: 'learn meditation techniques', action: 'learn', domain: 'health' },
  { text: 'analyze health metrics', action: 'analyze', domain: 'health' },
  { text: 'organize medical records', action: 'organize', domain: 'health' },
  { text: 'plan healthy meal prep', action: 'create', domain: 'health' },
  { text: 'book therapy session', action: 'schedule', domain: 'health' },
  { text: 'study stress management', action: 'learn', domain: 'health' },
  { text: 'track sleep patterns', action: 'analyze', domain: 'health' },
  { text: 'manage medication schedule', action: 'organize', domain: 'health' },
  { text: 'design exercise program', action: 'create', domain: 'health' },
  { text: 'schedule health checkup', action: 'schedule', domain: 'health' },
  { text: 'learn first aid skills', action: 'learn', domain: 'health' },
  { text: 'monitor blood pressure', action: 'analyze', domain: 'health' },
  { text: 'organize supplement routine', action: 'organize', domain: 'health' },
  { text: 'create mental health plan', action: 'create', domain: 'health' },
  { text: 'plan wellness retreat', action: 'schedule', domain: 'health' },
  { text: 'study nutrition science', action: 'learn', domain: 'health' },
  { text: 'evaluate fitness progress', action: 'analyze', domain: 'health' },
  { text: 'maintain health journal', action: 'organize', domain: 'health' },
  
  // EDUCATION & LEARNING (100 examples)
  { text: 'create study schedule', action: 'create', domain: 'education' },
  { text: 'schedule exam preparation', action: 'schedule', domain: 'education' },
  { text: 'learn new programming language', action: 'learn', domain: 'education' },
  { text: 'analyze test results', action: 'analyze', domain: 'education' },
  { text: 'organize study materials', action: 'organize', domain: 'education' },
  { text: 'design course curriculum', action: 'create', domain: 'education' },
  { text: 'plan tutoring sessions', action: 'schedule', domain: 'education' },
  { text: 'study for certification', action: 'learn', domain: 'education' },
  { text: 'review academic performance', action: 'analyze', domain: 'education' },
  { text: 'manage course notes', action: 'organize', domain: 'education' },
  { text: 'create educational content', action: 'create', domain: 'education' },
  { text: 'schedule online classes', action: 'schedule', domain: 'education' },
  { text: 'learn research methods', action: 'learn', domain: 'education' },
  { text: 'evaluate learning outcomes', action: 'analyze', domain: 'education' },
  { text: 'organize digital library', action: 'organize', domain: 'education' },
  { text: 'develop teaching materials', action: 'create', domain: 'education' },
  { text: 'plan workshop series', action: 'schedule', domain: 'education' },
  { text: 'study educational psychology', action: 'learn', domain: 'education' },
  { text: 'assess student progress', action: 'analyze', domain: 'education' },
  { text: 'maintain grade records', action: 'organize', domain: 'education' },
  
  // FINANCE & INVESTMENT (100 examples)
  { text: 'create investment portfolio', action: 'create', domain: 'finance' },
  { text: 'schedule financial review', action: 'schedule', domain: 'finance' },
  { text: 'learn stock market basics', action: 'learn', domain: 'finance' },
  { text: 'analyze market trends', action: 'analyze', domain: 'finance' },
  { text: 'organize financial documents', action: 'organize', domain: 'finance' },
  { text: 'plan retirement savings', action: 'create', domain: 'finance' },
  { text: 'book financial advisor meeting', action: 'schedule', domain: 'finance' },
  { text: 'study cryptocurrency', action: 'learn', domain: 'finance' },
  { text: 'track expense patterns', action: 'analyze', domain: 'finance' },
  { text: 'manage tax documents', action: 'organize', domain: 'finance' },
  { text: 'design budget plan', action: 'create', domain: 'finance' },
  { text: 'schedule bill payments', action: 'schedule', domain: 'finance' },
  { text: 'learn about bonds', action: 'learn', domain: 'finance' },
  { text: 'evaluate investment performance', action: 'analyze', domain: 'finance' },
  { text: 'organize receipts', action: 'organize', domain: 'finance' },
  { text: 'create emergency fund', action: 'create', domain: 'finance' },
  { text: 'plan tax preparation', action: 'schedule', domain: 'finance' },
  { text: 'study real estate investing', action: 'learn', domain: 'finance' },
  { text: 'analyze credit report', action: 'analyze', domain: 'finance' },
  { text: 'maintain financial records', action: 'organize', domain: 'finance' }
];

export const MEGA_DOMAINS = [
  'fitness', 'sports', 'cooking', 'music', 'art', 'travel', 'photography', 
  'video', 'gardening', 'gaming', 'health', 'education', 'finance', 'programming',
  'design', 'business', 'writing', 'science', 'medicine', 'psychology'
];

export const MEGA_ACTIONS = ['create', 'schedule', 'learn', 'communicate', 'analyze', 'organize'];