export const TRAINING_DATA = [
  // PLANNING - 50 examples
  { text: 'schedule meeting with john tomorrow', intent: 'planning' },
  { text: 'plan vacation next month', intent: 'planning' },
  { text: 'remind me to call mom', intent: 'planning' },
  { text: 'set deadline for project', intent: 'planning' },
  { text: 'book appointment with doctor', intent: 'planning' },
  { text: 'organize team lunch friday', intent: 'planning' },
  { text: 'plan birthday party for sarah', intent: 'planning' },
  { text: 'schedule dentist appointment', intent: 'planning' },
  { text: 'set reminder for grocery shopping', intent: 'planning' },
  { text: 'plan weekend trip to beach', intent: 'planning' },
  { text: 'organize conference call with clients', intent: 'planning' },
  { text: 'schedule workout session', intent: 'planning' },
  { text: 'plan study schedule for exams', intent: 'planning' },
  { text: 'book flight tickets for vacation', intent: 'planning' },
  { text: 'organize family dinner', intent: 'planning' },
  { text: 'schedule car maintenance', intent: 'planning' },
  { text: 'plan project timeline', intent: 'planning' },
  { text: 'set meeting with supervisor', intent: 'planning' },
  { text: 'organize team building event', intent: 'planning' },
  { text: 'schedule presentation for next week', intent: 'planning' },
  { text: 'plan budget for next quarter', intent: 'planning' },
  { text: 'book hotel for business trip', intent: 'planning' },
  { text: 'schedule interview with candidate', intent: 'planning' },
  { text: 'plan marketing campaign launch', intent: 'planning' },
  { text: 'organize product demo session', intent: 'planning' },
  { text: 'schedule training workshop', intent: 'planning' },
  { text: 'plan quarterly review meeting', intent: 'planning' },
  { text: 'book restaurant for anniversary', intent: 'planning' },
  { text: 'schedule maintenance window', intent: 'planning' },
  { text: 'plan content calendar', intent: 'planning' },
  { text: 'organize hackathon event', intent: 'planning' },
  { text: 'schedule code review session', intent: 'planning' },
  { text: 'plan sprint retrospective', intent: 'planning' },
  { text: 'book venue for conference', intent: 'planning' },
  { text: 'schedule one on one with team', intent: 'planning' },
  { text: 'plan product roadmap discussion', intent: 'planning' },
  { text: 'organize customer feedback session', intent: 'planning' },
  { text: 'schedule system upgrade', intent: 'planning' },
  { text: 'plan holiday schedule', intent: 'planning' },
  { text: 'book meeting room for presentation', intent: 'planning' },
  { text: 'schedule performance review', intent: 'planning' },
  { text: 'plan team outing', intent: 'planning' },
  { text: 'organize brainstorming session', intent: 'planning' },
  { text: 'schedule client onboarding', intent: 'planning' },
  { text: 'plan website redesign timeline', intent: 'planning' },
  { text: 'book conference tickets', intent: 'planning' },
  { text: 'schedule security audit', intent: 'planning' },
  { text: 'plan user testing session', intent: 'planning' },
  { text: 'organize all hands meeting', intent: 'planning' },
  { text: 'schedule deployment window', intent: 'planning' },

  // CODING - 50 examples
  { text: 'debug the api function', intent: 'coding' },
  { text: 'create new react project', intent: 'coding' },
  { text: 'deploy to github pages', intent: 'coding' },
  { text: 'build the frontend', intent: 'coding' },
  { text: 'fix authentication bug', intent: 'coding' },
  { text: 'implement user registration', intent: 'coding' },
  { text: 'optimize database queries', intent: 'coding' },
  { text: 'setup ci cd pipeline', intent: 'coding' },
  { text: 'refactor legacy code', intent: 'coding' },
  { text: 'add unit tests', intent: 'coding' },
  { text: 'configure webpack', intent: 'coding' },
  { text: 'setup docker container', intent: 'coding' },
  { text: 'implement payment gateway', intent: 'coding' },
  { text: 'create rest api endpoints', intent: 'coding' },
  { text: 'setup mongodb database', intent: 'coding' },
  { text: 'build mobile app', intent: 'coding' },
  { text: 'implement search functionality', intent: 'coding' },
  { text: 'setup authentication middleware', intent: 'coding' },
  { text: 'create admin dashboard', intent: 'coding' },
  { text: 'implement real time chat', intent: 'coding' },
  { text: 'setup redis caching', intent: 'coding' },
  { text: 'build recommendation engine', intent: 'coding' },
  { text: 'implement file upload', intent: 'coding' },
  { text: 'setup load balancer', intent: 'coding' },
  { text: 'create microservices architecture', intent: 'coding' },
  { text: 'implement oauth integration', intent: 'coding' },
  { text: 'setup monitoring dashboard', intent: 'coding' },
  { text: 'build data pipeline', intent: 'coding' },
  { text: 'implement machine learning model', intent: 'coding' },
  { text: 'setup kubernetes cluster', intent: 'coding' },
  { text: 'create graphql api', intent: 'coding' },
  { text: 'implement websocket connection', intent: 'coding' },
  { text: 'setup elasticsearch', intent: 'coding' },
  { text: 'build progressive web app', intent: 'coding' },
  { text: 'implement blockchain integration', intent: 'coding' },
  { text: 'setup terraform infrastructure', intent: 'coding' },
  { text: 'create automated testing suite', intent: 'coding' },
  { text: 'implement email service', intent: 'coding' },
  { text: 'setup cdn configuration', intent: 'coding' },
  { text: 'build analytics dashboard', intent: 'coding' },
  { text: 'implement push notifications', intent: 'coding' },
  { text: 'setup backup system', intent: 'coding' },
  { text: 'create api documentation', intent: 'coding' },
  { text: 'implement rate limiting', intent: 'coding' },
  { text: 'setup ssl certificates', intent: 'coding' },
  { text: 'build image processing service', intent: 'coding' },
  { text: 'implement two factor authentication', intent: 'coding' },
  { text: 'setup log aggregation', intent: 'coding' },
  { text: 'create deployment scripts', intent: 'coding' },
  { text: 'implement data validation', intent: 'coding' },

  // RESEARCH - 50 examples
  { text: 'research machine learning papers', intent: 'research' },
  { text: 'study quantum computing', intent: 'research' },
  { text: 'analyze market data', intent: 'research' },
  { text: 'investigate new framework', intent: 'research' },
  { text: 'study for chemistry exam', intent: 'research' },
  { text: 'research competitor analysis', intent: 'research' },
  { text: 'learn react native development', intent: 'research' },
  { text: 'study user behavior patterns', intent: 'research' },
  { text: 'research blockchain technology', intent: 'research' },
  { text: 'analyze customer feedback', intent: 'research' },
  { text: 'study artificial intelligence trends', intent: 'research' },
  { text: 'research sustainable energy solutions', intent: 'research' },
  { text: 'learn python programming', intent: 'research' },
  { text: 'study market segmentation', intent: 'research' },
  { text: 'research cloud computing platforms', intent: 'research' },
  { text: 'analyze website performance metrics', intent: 'research' },
  { text: 'study cybersecurity best practices', intent: 'research' },
  { text: 'research mobile app trends', intent: 'research' },
  { text: 'learn data science techniques', intent: 'research' },
  { text: 'study consumer psychology', intent: 'research' },
  { text: 'research emerging technologies', intent: 'research' },
  { text: 'analyze social media metrics', intent: 'research' },
  { text: 'study financial markets', intent: 'research' },
  { text: 'research ux design principles', intent: 'research' },
  { text: 'learn kubernetes orchestration', intent: 'research' },
  { text: 'study climate change data', intent: 'research' },
  { text: 'research startup funding options', intent: 'research' },
  { text: 'analyze conversion rates', intent: 'research' },
  { text: 'study neural network architectures', intent: 'research' },
  { text: 'research renewable energy trends', intent: 'research' },
  { text: 'learn advanced mathematics', intent: 'research' },
  { text: 'study supply chain optimization', intent: 'research' },
  { text: 'research digital marketing strategies', intent: 'research' },
  { text: 'analyze user engagement data', intent: 'research' },
  { text: 'study quantum physics principles', intent: 'research' },
  { text: 'research healthcare technology', intent: 'research' },
  { text: 'learn advanced sql queries', intent: 'research' },
  { text: 'study organizational behavior', intent: 'research' },
  { text: 'research space exploration missions', intent: 'research' },
  { text: 'analyze investment portfolios', intent: 'research' },
  { text: 'study machine learning algorithms', intent: 'research' },
  { text: 'research sustainable agriculture', intent: 'research' },
  { text: 'learn advanced statistics', intent: 'research' },
  { text: 'study economic indicators', intent: 'research' },
  { text: 'research biotechnology advances', intent: 'research' },
  { text: 'analyze customer journey mapping', intent: 'research' },
  { text: 'study renewable energy systems', intent: 'research' },
  { text: 'research autonomous vehicle technology', intent: 'research' },
  { text: 'learn advanced programming concepts', intent: 'research' },
  { text: 'study environmental science data', intent: 'research' },

  // COMMUNICATION - 50 examples
  { text: 'email the client about updates', intent: 'communication' },
  { text: 'email team about project updates', intent: 'communication' },
  { text: 'call sarah about the meeting', intent: 'communication' },
  { text: 'follow up with the team', intent: 'communication' },
  { text: 'send message to support', intent: 'communication' },
  { text: 'notify manager about progress', intent: 'communication' },
  { text: 'inform client of changes', intent: 'communication' },
  { text: 'update team on status', intent: 'communication' },
  { text: 'reach out to potential customers', intent: 'communication' },
  { text: 'contact vendor about delivery', intent: 'communication' },
  { text: 'send newsletter to subscribers', intent: 'communication' },
  { text: 'call customer service', intent: 'communication' },
  { text: 'email proposal to client', intent: 'communication' },
  { text: 'message team about deadline', intent: 'communication' },
  { text: 'notify stakeholders of delay', intent: 'communication' },
  { text: 'send invoice to customer', intent: 'communication' },
  { text: 'call supplier about order', intent: 'communication' },
  { text: 'email report to management', intent: 'communication' },
  { text: 'contact hr about policy', intent: 'communication' },
  { text: 'send reminder to attendees', intent: 'communication' },
  { text: 'call partner about collaboration', intent: 'communication' },
  { text: 'email feedback to developer', intent: 'communication' },
  { text: 'message client about requirements', intent: 'communication' },
  { text: 'notify users of maintenance', intent: 'communication' },
  { text: 'send thank you note', intent: 'communication' },
  { text: 'call investor about funding', intent: 'communication' },
  { text: 'email survey to customers', intent: 'communication' },
  { text: 'contact legal about contract', intent: 'communication' },
  { text: 'send announcement to staff', intent: 'communication' },
  { text: 'call mentor for advice', intent: 'communication' },
  { text: 'email presentation to board', intent: 'communication' },
  { text: 'message designer about mockups', intent: 'communication' },
  { text: 'notify press about launch', intent: 'communication' },
  { text: 'send welcome email to new user', intent: 'communication' },
  { text: 'call conference organizer', intent: 'communication' },
  { text: 'email agenda to participants', intent: 'communication' },
  { text: 'contact accountant about taxes', intent: 'communication' },
  { text: 'send update to investors', intent: 'communication' },
  { text: 'call tech support', intent: 'communication' },
  { text: 'email contract to lawyer', intent: 'communication' },
  { text: 'message recruiter about candidate', intent: 'communication' },
  { text: 'notify customers of new feature', intent: 'communication' },
  { text: 'send birthday wishes', intent: 'communication' },
  { text: 'call insurance agent', intent: 'communication' },
  { text: 'email specifications to vendor', intent: 'communication' },
  { text: 'contact journalist about story', intent: 'communication' },
  { text: 'send apology to customer', intent: 'communication' },
  { text: 'call bank about loan', intent: 'communication' },
  { text: 'email minutes to committee', intent: 'communication' },
  { text: 'message colleague about project', intent: 'communication' },

  // CREATIVE - 50 examples
  { text: 'design new logo concept', intent: 'creative' },
  { text: 'write blog post about ai', intent: 'creative' },
  { text: 'brainstorm app ideas', intent: 'creative' },
  { text: 'sketch user interface', intent: 'creative' },
  { text: 'create marketing campaign', intent: 'creative' },
  { text: 'design website mockup', intent: 'creative' },
  { text: 'write product description', intent: 'creative' },
  { text: 'create social media content', intent: 'creative' },
  { text: 'design business card', intent: 'creative' },
  { text: 'write press release', intent: 'creative' },
  { text: 'create video script', intent: 'creative' },
  { text: 'design mobile app interface', intent: 'creative' },
  { text: 'write email newsletter', intent: 'creative' },
  { text: 'create brand guidelines', intent: 'creative' },
  { text: 'design poster for event', intent: 'creative' },
  { text: 'write user stories', intent: 'creative' },
  { text: 'create infographic design', intent: 'creative' },
  { text: 'design packaging concept', intent: 'creative' },
  { text: 'write technical documentation', intent: 'creative' },
  { text: 'create presentation slides', intent: 'creative' },
  { text: 'design t shirt graphics', intent: 'creative' },
  { text: 'write advertising copy', intent: 'creative' },
  { text: 'create wireframe layouts', intent: 'creative' },
  { text: 'design book cover', intent: 'creative' },
  { text: 'write case study', intent: 'creative' },
  { text: 'create animation storyboard', intent: 'creative' },
  { text: 'design restaurant menu', intent: 'creative' },
  { text: 'write product manual', intent: 'creative' },
  { text: 'create podcast artwork', intent: 'creative' },
  { text: 'design trade show booth', intent: 'creative' },
  { text: 'write grant proposal', intent: 'creative' },
  { text: 'create user journey map', intent: 'creative' },
  { text: 'design magazine layout', intent: 'creative' },
  { text: 'write white paper', intent: 'creative' },
  { text: 'create brand identity', intent: 'creative' },
  { text: 'design web banner ads', intent: 'creative' },
  { text: 'write product roadmap', intent: 'creative' },
  { text: 'create style guide', infographic: 'creative' },
  { text: 'design mobile wallpaper', intent: 'creative' },
  { text: 'write feature specifications', intent: 'creative' },
  { text: 'create mood board', intent: 'creative' },
  { text: 'design email template', intent: 'creative' },
  { text: 'write marketing strategy', intent: 'creative' },
  { text: 'create prototype design', intent: 'creative' },
  { text: 'design conference badge', intent: 'creative' },
  { text: 'write user manual', intent: 'creative' },
  { text: 'create dashboard layout', intent: 'creative' },
  { text: 'design product catalog', intent: 'creative' },
  { text: 'write creative brief', intent: 'creative' },
  { text: 'create icon set design', intent: 'creative' }
];

export const INTENT_LABELS = ['planning', 'coding', 'research', 'communication', 'creative'];
export const LABEL_TO_INDEX = {
  'planning': 0,
  'coding': 1,
  'research': 2,
  'communication': 3,
  'creative': 4
};