import React, { useState } from 'react';
import { Download, AlertTriangle, FileText } from 'lucide-react';

interface DownloadConfirmationProps {
  fileName: string;
  fileType: string;
  purpose: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export default function DownloadConfirmation({ 
  fileName, 
  fileType, 
  purpose, 
  onConfirm, 
  onCancel 
}: DownloadConfirmationProps) {
  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-gray-900 border border-yellow-400/30 rounded-xl p-6 max-w-md w-full">
        <div className="flex items-center gap-3 mb-4">
          <AlertTriangle className="w-6 h-6 text-yellow-400" />
          <h3 className="text-xl font-bold text-yellow-300">Download Confirmation</h3>
        </div>
        
        <div className="space-y-3 mb-6">
          <div className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-400" />
            <span className="text-sm text-gray-300">File: <span className="text-white font-medium">{fileName}</span></span>
          </div>
          
          <div className="flex items-center gap-2">
            <Download className="w-4 h-4 text-green-400" />
            <span className="text-sm text-gray-300">Type: <span className="text-white font-medium">{fileType}</span></span>
          </div>
          
          <div className="bg-blue-900/20 border border-blue-400/20 rounded p-3">
            <p className="text-sm text-blue-200">
              <strong>Purpose:</strong> {purpose}
            </p>
          </div>
          
          <div className="bg-green-900/20 border border-green-400/20 rounded p-3">
            <p className="text-xs text-green-300">
              ✅ Safe file generated by Cognitive OS<br/>
              ✅ No executable code - just helpful content<br/>
              ✅ You can review before using
            </p>
          </div>
        </div>
        
        <div className="flex gap-3">
          <button
            onClick={onCancel}
            className="flex-1 bg-gray-600 hover:bg-gray-700 text-white px-4 py-2 rounded-lg transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={onConfirm}
            className="flex-1 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg transition-colors flex items-center justify-center gap-2"
          >
            <Download className="w-4 h-4" />
            Download
          </button>
        </div>
      </div>
    </div>
  );
}